# Quant Finance Modelling:

In [1]:
# Data manipulation & visualization libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
%matplotlib inline
import warnings

In [2]:
loans = pd.read_csv('Data.csv', sep = ';')

In [3]:
loans.drop(columns="Unnamed: 0", inplace=True)

### Explain the dataset:
- origination amount = the loan amount provided by the lending company per month.
- the other columns = the repayment amount for each month.
- every row represents a month/ vintage (ranging from June 2019 - December 2020).

In [11]:
loans.head()

,Origination Amount,31.05.2019,30.06.2019,31.07.2019,31.08.2019,30.09.2019,31.10.2019,30.11.2019,31.12.2019,31.01.2020,...,31.03.2020,30.04.2020,31.05.2020,30.06.2020,31.07.2020,31.08.2020,30.09.2020,31.10.2020,30.11.2020,31.12.2020
0,10018746.17,1443069.08,3332200.33,1328138.75,928085.74,736418.27,539403.31,427557.86,324459.32,237056.39,...,116684.68,92699.67,63399.66,53265.12,37121.13,29787.10,24524.90,18085.94,16581.01,11442.97
1,10868379.04,0.00,1392751.60,3011884.91,1237868.70,970929.28,892351.83,668767.02,505612.59,419598.74,...,255222.42,198833.96,161996.73,138461.91,92346.68,79641.30,63457.44,52373.85,43374.70,37404.87
2,10733932.61,0.00,0.00,1537650.24,2953335.55,1208316.08,879375.19,711016.84,658251.40,503465.03,...,302575.54,258652.52,191798.05,170027.54,127574.33,110301.21,89766.69,64746.84,61408.92,50312.70
3,12558727.02,0.00,0.00,0.00,1617681.94,4082016.00,1387474.94,1247623.59,886293.35,694348.63,...,417223.56,336686.08,253556.20,200066.59,151859.74,109973.00,90228.14,70661.50,53102.83,47069.84
4,14505071.44,0.00,0.00,0.00,0.00,1992242.84,3930445.60,1394620.78,1227905.58,939424.54,...,628429.48,589692.85,457299.31,323764.87,288152.28,239872.99,192246.98,171550.69,142575.97,116853.05

In [12]:
#all the variables are numeric
loans.dtypes

Origination Amount    float64
31.05.2019            float64
30.06.2019            float64
31.07.2019            float64
31.08.2019            float64
30.09.2019            float64
31.10.2019            float64
30.11.2019            float64
31.12.2019            float64
31.01.2020            float64
29.02.2020            float64
31.03.2020            float64
30.04.2020            float64
31.05.2020            float64
30.06.2020            float64
31.07.2020            float64
31.08.2020            float64
30.09.2020            float64
31.10.2020            float64
30.11.2020            float64
31.12.2020            float64
dtype: object

In [13]:
loans.describe().round()

,Origination Amount,31.05.2019,30.06.2019,31.07.2019,31.08.2019,30.09.2019,31.10.2019,30.11.2019,31.12.2019,31.01.2020,...,31.03.2020,30.04.2020,31.05.2020,30.06.2020,31.07.2020,31.08.2020,30.09.2020,31.10.2020,30.11.2020,31.12.2020
count,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,...,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0,20.0
mean,19939467.0,72153.0,236248.0,293884.0,336849.0,449496.0,495925.0,564711.0,615107.0,649298.0,...,757576.0,830565.0,853358.0,956545.0,1005886.0,974952.0,1044697.0,959118.0,1078137.0,1057797.0
std,6563824.0,322680.0,792300.0,777053.0,776748.0,1014007.0,1014547.0,1143841.0,1159722.0,1214030.0,...,1457239.0,1517052.0,1573937.0,1811136.0,2054033.0,1860876.0,1959497.0,1672878.0,2055731.0,1978896.0
min,10018746.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11443.0
25%,14957053.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,27841.0,67178.0,83189.0,69183.0,122284.0,118658.0
50%,20422651.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,185954.0,228743.0,222677.0,261916.0,323412.0,295665.0,338924.0,341443.0,340709.0,403307.0
75%,25578379.0,0.0,0.0,0.0,0.0,184105.0,624396.0,679329.0,715262.0,755618.0,...,805323.0,836217.0,841648.0,911670.0,966594.0,985200.0,1030446.0,956525.0,1003413.0,984122.0
max,30482979.0,1443069.0,3332200.0,3011885.0,2953336.0,4082016.0,3930446.0,4682354.0,4637702.0,4947764.0,...,6142911.0,6228478.0,6476252.0,7636996.0,8983764.0,8030091.0,8374135.0,7065477.0,8752707.0,8383025.0

In [7]:
#every repayment's share of the origination amount.

loans_2 = loans.copy()
loans_2

,Origination Amount,31.05.2019,30.06.2019,31.07.2019,31.08.2019,30.09.2019,31.10.2019,30.11.2019,31.12.2019,31.01.2020,...,31.03.2020,30.04.2020,31.05.2020,30.06.2020,31.07.2020,31.08.2020,30.09.2020,31.10.2020,30.11.2020,31.12.2020
0,10018746.17,1443069.08,3332200.33,1328138.75,928085.74,736418.27,539403.31,427557.86,324459.32,237056.39,...,116684.68,92699.67,63399.66,53265.12,37121.13,29787.10,24524.90,18085.94,16581.01,11442.97
1,10868379.04,0.00,1392751.60,3011884.91,1237868.70,970929.28,892351.83,668767.02,505612.59,419598.74,...,255222.42,198833.96,161996.73,138461.91,92346.68,79641.30,63457.44,52373.85,43374.70,37404.87
2,10733932.61,0.00,0.00,1537650.24,2953335.55,1208316.08,879375.19,711016.84,658251.40,503465.03,...,302575.54,258652.52,191798.05,170027.54,127574.33,110301.21,89766.69,64746.84,61408.92,50312.70
3,12558727.02,0.00,0.00,0.00,1617681.94,4082016.00,1387474.94,1247623.59,886293.35,694348.63,...,417223.56,336686.08,253556.20,200066.59,151859.74,109973.00,90228.14,70661.50,53102.83,47069.84
4,14505071.44,0.00,0.00,0.00,0.00,1992242.84,3930445.60,1394620.78,1227905.58,939424.54,...,628429.48,589692.85,457299.31,323764.87,288152.28,239872.99,192246.98,171550.69,142575.97,116853.05
5,15652952.20,0.00,0.00,0.00,0.00,0.00,2289453.76,4682354.31,1659503.89,1165897.09,...,763523.36,742787.97,558085.95,461806.22,358671.23,281881.11,241719.91,182730.05,144953.58,119260.10
6,15107713.30,0.00,0.00,0.00,0.00,0.00,0.00,2162283.09,4637701.69,1576348.23,...,930720.35,697500.94,667277.73,547749.09,387987.02,309448.86,283876.04,215635.85,185516.45,141560.57
7,17004745.04,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2402403.37,4947764.21,...,1245452.39,1116505.94,803590.21,724956.28,545397.33,458832.95,393971.01,333818.53,286831.44,216447.57
8,16794379.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2502066.86,...,1505493.21,1182983.95,955821.48,846061.73,683116.81,560572.44,468203.76,349067.92,309854.99,267813.78
9,19217205.82,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,6142911.08,1833677.81,1317065.75,1108494.37,918465.33,719913.69,587381.96,498801.31,371563.77,294941.22
10,21628095.29,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,2843285.54,6228477.78,1585123.49,1425436.30,1110978.39,956265.05,815621.71,684971.52,644953.50,511673.76
11,22334728.88,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,3332800.29,6476251.76,1747437.15,1419428.65,1072005.46,977346.88,836368.52,617274.49,547562.79
12,22393345.39,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,3575896.21,7636995.58,1542705.08,1376501.77,1189742.70,888608.29,676918.44,626450.24
13,24671655.23,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,3746372.58,8983764.16,1653631.68,1512916.37,1160275.72,945057.64,747172.11
14,25478232.23,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,3470149.61,8030091.09,1612000.20,1357290.46,1178479.01,945964.38
15,25878820.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,3510328.95,8374134.70,1564208.19,1362121.91,1098593.34
16,25887161.41,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,3976808.32,7065477.24,1385481.66,1115017.68
17,27699586.46,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3667678.21,8752706.73,1503544.68
18,29872889.68,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4383982.78,8383025.07
19,30482978.52,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4373830.97

### Compute the historical repayment percentages, i.e. every repaymentâ€™s share of the origination amount.

In [8]:
for index, vintage in loans_2.iterrows():
    
    cumulative_repayments = vintage[1:].cumsum() 
    # Divide by the origination amount and multiply by 100 to get the percentage
    percentage = (cumulative_repayments / vintage['Origination Amount']) * 100

    # Store the result in the new column
    loans_2.at[index, 'Historical_Repayments_Percentage'] = percentage.iloc[-1]

In [18]:
loans_2.head()

,Origination Amount,31.05.2019,30.06.2019,31.07.2019,31.08.2019,30.09.2019,31.10.2019,30.11.2019,31.12.2019,31.01.2020,...,30.06.2020,31.07.2020,31.08.2020,30.09.2020,31.10.2020,30.11.2020,31.12.2020,Historical_Repayments_Percentage,Total Repayments,Repayment Percentage
0,10018746.17,1443069.08,3332200.33,1328138.75,928085.74,736418.27,539403.31,427557.86,324459.32,237056.39,...,53265.12,37121.13,29787.10,24524.90,18085.94,16581.01,11442.97,99.097688,9.928445e+06,99.098677
1,10868379.04,0.00,1392751.60,3011884.91,1237868.70,970929.28,892351.83,668767.02,505612.59,419598.74,...,138461.91,92346.68,79641.30,63457.44,52373.85,43374.70,37404.87,97.090295,1.055224e+07,97.091188
2,10733932.61,0.00,0.00,1537650.24,2953335.55,1208316.08,879375.19,711016.84,658251.40,503465.03,...,170027.54,127574.33,110301.21,89766.69,64746.84,61408.92,50312.70,95.972467,1.030172e+07,95.973361
3,12558727.02,0.00,0.00,0.00,1617681.94,4082016.00,1387474.94,1247623.59,886293.35,694348.63,...,200066.59,151859.74,109973.00,90228.14,70661.50,53102.83,47069.84,97.278095,1.221699e+07,97.278869
4,14505071.44,0.00,0.00,0.00,0.00,1992242.84,3930445.60,1394620.78,1227905.58,939424.54,...,323764.87,288152.28,239872.99,192246.98,171550.69,142575.97,116853.05,92.643108,1.343804e+07,92.643747